import { Lang } from '@/types'

// ─── helpers ──────────────────────────────────────────────────────────────────
// NOTE: Zero pre-scripted NPC dialogue exists in this file.
// All NPC responses are generated by Claude API via /api/chat.
// This file only contains UI strings and hint data.

export type DV = { ko: string; en: string }

export function t(v: DV, lang: Lang): string {
  return v[lang] ?? v.en ?? v.ko ?? ''
}

// ─── UI strings ───────────────────────────────────────────────────────────────

export const UI = {
  inputPlaceholder: { ko: '메시지를 입력하세요...', en: 'type a message...' } as DV,
  sendButton:        { ko: '전송', en: 'send' } as DV,
  emptyChat:         { ko: '대화를 시작해 보세요.', en: 'say something...' } as DV,
  emptyChatJames:    { ko: '잠시 후 James가 인사를 건넵니다...', en: 'James will say hello shortly...' } as DV,
}

export const HINT_POPUP_LABEL: DV = {
  ko: '💡 표현 힌트',
  en: '💡 expression hints',
}

// ─── Hint data ────────────────────────────────────────────────────────────────

export interface Hint {
  english: string
  korean: string
  context: string
}

export const HINTS_EP01: Hint[] = [
  { english: "Nice to meet you. I'm [name], new to the team.", korean: '만나서 반갑습니다. 저는 팀에 새로 합류한 [이름]입니다.', context: '첫 자기소개' },
  { english: 'Could you show me how this works?', korean: '이게 어떻게 사용되는지 보여주실 수 있나요?', context: '도움 요청' },
  { english: "I'll get right on it.", korean: '바로 처리하겠습니다.', context: '업무 수락' },
  { english: 'Just to confirm — I should finish this by end of day, correct?', korean: '확인차 여쭤보는데요, 오늘 안으로 완료하면 되는 거 맞나요?', context: '업무 확인' },
  { english: 'Thank you so much for your help.', korean: '도움 주셔서 정말 감사드립니다.', context: '감사 표현' },
]

export const HINTS_TASK_TRIGGER: Hint[] = [HINTS_EP01[2], HINTS_EP01[1], HINTS_EP01[3]]
